//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassRegister
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klasa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Klasa()
        {
            this.Obecnosc = new HashSet<Obecnosc>();
            this.OcenyUcznia = new HashSet<OcenyUcznia>();
        }
    
        public long IdUcznia { get; set; }
        public string Nazwisko { get; set; }
        public string Imie { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obecnosc> Obecnosc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OcenyUcznia> OcenyUcznia { get; set; }
    }
}
